package eu.kanade.tachiyomi

// AUTO-GENERATED by rebrand/REBRAND.sh from rebrand/default_repos.json — do not hand-edit.
// TOMAHAWK: default extension-repo index URLs seeded on first launch (see App.seedTomahawkDefaultRepos).
object TomahawkDefaultRepos {
    val indexUrls: List<String> = listOf(
        "https://raw.githubusercontent.com/yuzono/anime-repo/repo/index.min.json",
        "https://raw.githubusercontent.com/Secozzi/aniyomi-extensions/refs/heads/repo/index.min.json",
        "https://raw.githubusercontent.com/rentaroarvin/rentaro-repo/repo/index.min.json",
        "https://raw.githubusercontent.com/salmanbappi/extensions-repo/main/index.min.json",
    )
}
